In [ ]:
#1
import numpy as np
from sklearn.model_selection import train_test_split
# from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd


df = pd.read_csv('tips.csv')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df["tip_percent"] = df.apply(lambda x: x.tip / x.total_bill, axis=1)
df.head()

# 1 
df_time_mean = df.groupby("time")["tip_percent"].mean()
df_time_mean

time
Dinner    0.159518
Lunch     0.164128
Name: tip_percent, dtype: float64

In [ ]:
# 2 mean for each day
df_day_mean = df.groupby("day")["tip_percent"].mean()
df_day_mean

day
Fri     0.169913
Sat     0.153152
Sun     0.166897
Thur    0.161276
Name: tip_percent, dtype: float64

In [ ]:
# 3 highest for which day and time
df_day_mean = df.groupby(["day", "time"])["tip_percent"].mean()
df_day_mean

# form the table below we can see Friday/ Lunch is the highest

day   time
Fri   Dinner    0.158916
      Lunch     0.188765
Sat   Dinner    0.153152
Sun   Dinner    0.166897
Thur  Dinner    0.159744
      Lunch     0.161301
Name: tip_percent, dtype: float64

In [ ]:
# 4 correlation
df[["total_bill", "tip"]].corr()

# from the table below correlation = 0.676

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

In [ ]:
# 5 
df[["size", "tip"]].corr()

# Since the correlation = 0.49, There does exist relationship between tips and size

          size       tip
size  1.000000  0.489299
tip   0.489299  1.000000

In [ ]:
# 6 percent of smoker is 38.1%
np.mean(df["smoker"].values == "Yes")

0.38114754098360654

In [ ]:
# 7 
df.shape

day_num = 0
prev_day = None
inday_index = 1
def index_day(new_day):
    global day_num, prev_day, inday_index
#     print(new_day)
    if prev_day is None:
        prev_day = new_day
        day_num += 1
        inday_index = 1
    elif prev_day == new_day:
        inday_index += 1
        pass
    else:
        prev_day = new_day
        day_num += 1
        inday_index = 1
        
    return day_num* 1000 + inday_index
    


df["day_tag"] = df.day.apply(index_day)
df["day_NO"] = df.day_tag // 1000
df["inday_index"] = df.day_tag % 1000
min_dayNo = df.day_NO.min()
max_dayNo = df.day_NO.max()
min_dayNo, max_dayNo
for cur_day in range (min_dayNo, max_dayNo + 1):
    df_day = df[df.day_NO == cur_day]
    print(f"day = {cur_day} corr between index and tip", df_day[["inday_index", "tip"]].corr().iloc[0, 1])
    
# from the table below, we can see some times the corr is positive, which 
# means tips are increasing with time in that day. While sometimes, the corr is negtive, which
# means tips are decreasing with time in this day.

day = 1 corr between index and tip 0.1952458483043091
day = 2 corr between index and tip -0.16449596340104336
day = 3 corr between index and tip 0.0527418137756666
day = 4 corr between index and tip -0.08648426722783391
day = 5 corr between index and tip 0.23676237012198015
day = 6 corr between index and tip -0.19606519688949917
day = 7 corr between index and tip -0.17294809454985013
day = 8 corr between index and tip 0.5344677097827352
day = 9 corr between index and tip 0.16589225360254894
day = 10 corr between index and tip 0.11629368573571641
day = 11 corr between index and tip 0.41584189551973005
day = 12 corr between index and tip -0.10818826134885774
day = 13 corr between index and tip -0.014056746773678512
day = 14 corr between index and tip -0.11555959019107354
day = 15 corr between index and tip -0.3374831964839026
day = 16 corr between index and tip -0.027014136494830795
day = 17 corr between index and tip nan

In [ ]:
# 8 firstly change smoke into lable
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["smoke_lab"] = le.fit_transform(df.smoker)
df.tail(30)

df[["smoke_lab", "tip"]].corr()

# since the corr = 0.6%, we can assume there is no difference

           smoke_lab       tip
smoke_lab   1.000000  0.005929
tip         0.005929  1.000000